/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void rollTest(){
        App classUnderTest = new App();

        assertEquals(2, classUnderTest.roll(2).length, "Test failed check your parameters");

    }

    @Test
    void containsDuplicatesTest(){
        App classUnderTest = new App();

        int[] arr = {1, 2, 3, 1};
        assertEquals(true,classUnderTest.containsDuplicates(arr), "Test failed check your parameters");

    }
    @Test
    void temperaturesTest(){
        App classUnderTest = new App();
        double[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        double[] expectedAverages = {63.0, 63.57142857142857, 57.0, 57.42857142857143};

        assertArrayEquals(expectedAverages ,classUnderTest.temperatures(weeklyMonthTemperatures),"Test failed check your parameters");

    }
}
